# Complete numpy course sheet

In [2]:
# create 0 Dimension array
import numpy as np
a= np.array(1)
a

array(1)

In [3]:
#  check dimension
print(a.ndim)

0


In [4]:
# create 1 Dimension array
b= np.array([1,2,3])
b

array([1, 2, 3])

In [5]:
#  check dimension
print(b.ndim)

1


In [6]:
# create 2 Dimension array
c= np.array([[1,2,7],[1,2,3]])
c

array([[1, 2, 7],
       [1, 2, 3]])

In [7]:
#  check dimension
print(c.ndim)

2


In [8]:
# create 3 Dimension array
d= np.array([[[1,2],[1,2]],[[1,2],[1,2]]])
d

array([[[1, 2],
        [1, 2]],

       [[1, 2],
        [1, 2]]])

In [9]:
#  check dimension
print(d.ndim)

3


In [10]:
# create dimension using ndmin
a= np.array([1,2,3,4],ndmin=1)
a

array([1, 2, 3, 4])

In [11]:
# using indexing or operators we can find solutions whatever you want
a[3]*2+a[2]

11

In [12]:
# indexing
a= np.array([[1,2,7],[1,2,3]])
a[1,2]

3

In [13]:
# step indexing
a= np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
a

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [14]:
a[0,1,-2]

3

In [15]:
# slicing
a=np.array([1,2,3,4,5])
a[1:4]

array([2, 3, 4])

In [16]:
# negetive slicing
a[-3:-1]

array([3, 4])

In [17]:
# slicing step
a=np.array([1,2,3,4,5,6,7])
a[0:8:2]

array([1, 3, 5, 7])

In [18]:
a[::2]

array([1, 3, 5, 7])

In [19]:
a= np.array([[1,2,3,4,5],[6,7,8,9,10]])

In [20]:
a[0,0:6:2]

array([1, 3, 5])

In [21]:
a[0:2,3]

array([4, 9])

In [22]:
a[0:2,1:4]

array([[2, 3, 4],
       [7, 8, 9]])

In [23]:
# dtype using for known datatype
a.dtype

dtype('int64')

In [24]:
# create array using float value
a=np.array([1.1,1.2,1.7])
a

array([1.1, 1.2, 1.7])

In [25]:
# change type using astype float to int
new=a.astype(int)
new

array([1, 1, 1])

In [26]:
# change type using astype  int to complex
new.astype(complex)

array([1.+0.j, 1.+0.j, 1.+0.j])

In [27]:
# change value using index
a=np.array([1,2,3,4,5,6,7])
a[0]=2
a

array([2, 2, 3, 4, 5, 6, 7])

In [28]:
# using view we can visible same dimensions value to another
y=a.view()
y

array([2, 2, 3, 4, 5, 6, 7])

In [29]:
# using shape can find how much rows and columns
a= np.array([[1,2,3,4,5],[6,7,8,9,10]])
a.shape

(2, 5)

In [30]:
# using reshape for giving new shape to an array without changing its elements
a=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
a.reshape(3,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [31]:
a.reshape(-2,6,1)

array([[[ 1],
        [ 2],
        [ 3],
        [ 4],
        [ 5],
        [ 6]],

       [[ 7],
        [ 8],
        [ 9],
        [10],
        [11],
        [12]]])

In [32]:
# itterate in three dimension using 3 loop
a= np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
for i in a:
    for s in i:
        for z in s:
            print(z)

1
2
3
4
5
6
7
8


In [33]:
# concatenation in one dimension
a=np.array([1,2,3])
b=np.array([4,5,6])
c=np.concatenate((a,b))
c

array([1, 2, 3, 4, 5, 6])

In [34]:
# concatenation in two dimension on (column using axis=1)
a=np.array([[1,2],[3,4]])
b=np.array([[1,2],[3,4]])
c=np.concatenate((a,b),axis=1)
c

array([[1, 2, 1, 2],
       [3, 4, 3, 4]])

In [35]:
d=np.concatenate((a,b),axis=0)
d

array([[1, 2],
       [3, 4],
       [1, 2],
       [3, 4]])

In [36]:
# join using stack()
a=np.array([1,2,3])
b=np.array([4,5,6])
c=np.stack((a,b))
c

array([[1, 2, 3],
       [4, 5, 6]])

In [37]:
# using join for hstack
a=np.array([1,2,3])
b=np.array([4,5,6])
c=np.hstack((a,b))
c

array([1, 2, 3, 4, 5, 6])

In [38]:
#dstack using for knowing depth
c=np.dstack((a,b))
c

array([[[1, 4],
        [2, 5],
        [3, 6]]])

In [39]:
a=np.array([1, 2, 3, 4, 5, 6])
b=np.array_split(a,10)
b

[array([1]),
 array([2]),
 array([3]),
 array([4]),
 array([5]),
 array([6]),
 array([], dtype=int64),
 array([], dtype=int64),
 array([], dtype=int64),
 array([], dtype=int64)]